name: dart_todo
description: Todo app
version: 0.7.0
author: Mike Zrimsek

environment:
  sdk: '>=1.20.0 <2.0.0'

dependencies:
  aqueduct: ^1.0.4
  angular2: ^2.2.0
  mime: ^0.9.3
  path: ^1.4.1
  http: ^0.11.0
  stream_transformers: ^0.3.0
dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: any

transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    - 'package:angular2/common.dart#FORM_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
    resolved_identifiers:
        BrowserClient: 'package:http/browser_client.dart'
        Client: 'package:http/http.dart'
- $dart2js:
    minify: true
    commandLineOptions: [--show-package-warnings, --dump-info, --enable-experimental-mirrors]
- dart_to_js_script_rewriter
